### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by Nag94** [Lybron/health-auto-export#13]
**Description**
Problem with authentication on Home Assistant Addon Mosquito Broker (v6.1.2)  for MQTT Export.

In mosquito Broker logs, have the following : 

1660474197: New connection from 192.168.1.253:60562 on port 1883.
error: received null username or password for unpwd check

But, the user and password are well set in the application. All my other devices using mqtt with authentication have no problems.

**Steps To Reproduce**
1. Create a new Automation with type MQTT
2. Set IP, port, topic, user, password
3. Save
4. Try Export Manually

**Expected behavior**
Normally, MQTT connection must use the user and password , but it seems not.

** iOS/watchOS : **
 - Device: Iphone 11 Pro
 - OS: IOS
 - Version 15.6
- App Version: 6.3

**Comment by Lybron** [comment]
Thanks for reporting. I'll have a look into it and come back with any questions if I'm unable to reproduce it.

**Comment by michaelblight** [comment]
Maybe related to this, I created an auto-export to MQTT to run every 5 minutes. When I open it in the app, it is shown for a short time, and then crashes the app. If I go into the app and do nothing, after a while the whole app locks up and I have to force-quit it (maybe when trying to run it after 5 minutes?). I have restarted the iPhone and the problem still occurs.

As a result I think it has also stopped my existing export to Home Assistant because I only have that run every 30 minutes, and by then the app has locked. I will probably next try deleting the app and re-installing.

**Comment by alphasixtyfive** [comment]
I confirm getting identical error: 

```
2022-11-02 18:20:06: New connection from 192.168.1.112:54165 on port 1883.
error: received null username or password for unpwd check
```

**Comment by Lybron** [comment]
Hi everyone, thanks for your reporting on this issue. I am currently preparing a beta to fix this issue and would appreciate if you could test it out to ensure it works before publishing on the App Store.

If you check the Health Auto Export app and navigate to Settings, there is an option to Join the TestFlight Beta if you haven't already.

The app version will be 6.4.2 and I expect it would make it through beta app review by some time tomorrow.

**Comment by Lybron** [comment]
[Version 6.5](https://apple.co/3iqbU2d) is now available and should resolve this issue, but do reopen the but report if it hasn't.
