### ISSUE TITLE
[Feature Request] - Medication data

### ISSUE THREAD

**Issue by mfgrcia** [Lybron/health-auto-export#15]
Are you planning to add medication data to the export? It would be a nice addition, thanks.

**Comment by Lybron** [comment]
Hi,

Thanks for the feature request. I've had this a few times.

Unfortunately, Apple does not allow third-party developers to access medication data added to the Health app. Developers cannot read nor modify this data. There is no indication at this moment when or if this will ever change but I do know several developers have given feedback to the engineering team responsible that this is requested.

I'll close this for the moment, since there's no real action that can be taken. Rest assured, I'll be adding support whenever Apple changes the policy on this data :)
